### ISSUE TITLE
Buttons too close

### ISSUE THREAD

**Issue by jsvini** [Runrunit/chrome-extension#11]
The "complete task" button is too close to the play/pause button, the misclick happens a lot in my team.

How it is:
![image](https://user-images.githubusercontent.com/4185886/48916586-adce0a80-ee61-11e8-9118-25cd88fad686.png)

Fixed :)

![image](https://user-images.githubusercontent.com/4185886/48916775-6eec8480-ee62-11e8-8c29-89ee3c3a0920.png)

```css
.style__RunrunItem__completeBtn___1NVJq{
  float: right;
  margin-left: 6px;
}
```

Do you guys accept pull requests?
